### ISSUE TITLE
The implementation is seemingly inconsistent with the paper. Is this a bug?

### ISSUE THREAD

**Issue by ZillaRU** [isjakewong/MIRACLE#3]
Hello! I have one more confusing issue now...
As you wrote in Formula (11) and (12) (Section 2.5.2) of your paper published on WWW'21, the disagreement loss should measure the intra- and inter-view's disagreement on  **UNLABELED** drug pairs. 
![image](https://user-images.githubusercontent.com/25343084/142145273-0c94aa6e-c811-4738-979e-57c7e327b224.png)

But in your implementation, the disagreement quantified by KL divergence is calculated on the **LABELED** drug pairs using the `adj_mask` rather than `adj_mask_un `. The `adj_mask_un ` is never used in loss computation. Is this a bug?
https://github.com/isjakewong/MIRACLE/blob/61ab653d41d095227cb9d0778b0780fe3afe4724/MIRACLE/main.py#L265
https://github.com/isjakewong/MIRACLE/blob/61ab653d41d095227cb9d0778b0780fe3afe4724/MIRACLE/main.py#L266
https://github.com/isjakewong/MIRACLE/blob/61ab653d41d095227cb9d0778b0780fe3afe4724/MIRACLE/main.py#L312
Thanks in advance! XD

**Comment by isjakewong** [comment]
Thanks for pointing this typo out! I have updated the related files.

**Comment by ZillaRU** [comment]
> 

My pleasure~ I will conduct experiments on my datasets using your updated implementation.
