### ISSUE TITLE
have the implementation done correctly?

### ISSUE THREAD

**Issue by Namkyeong** [isjakewong/MIRACLE#4]
![스크린샷 2022-09-06 오후 12 12 38](https://user-images.githubusercontent.com/40378824/188539310-8e320392-ee8c-4433-880d-f3cc82e9ef5a.png)

Hello authors
thank you for your great work predicting drug-drug interactions!

I have questions on the implementation.
Where can I find the interaction prediction in the code?
It seems like the model simply predict the interaction between drug i and j using only feature of i.

Thank you!
Namkyeong

**Comment by isjakewong** [comment]
Hi, in this final version, we directly use a FFN to predict the interaction score. The reason why we simplify this operation is that drug synergy information has been flowing into each other in previous message-aggregating and further contrastive learning. Thus, we can easily apply a FFN to disentangle the hidden patterns for prediction. Maybe you could try cross-attention to improve the fusion of different drug representations.
